sudo: required
dist: trusty
language: cpp
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-4.9 git curl
    - sudo apt-get upgrade -qq libstdc++6
    - curl -L http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl/download -o devkitARMupdate.pl
    - chmod +x ./devkitARMupdate.pl
    - sudo ./devkitARMupdate.pl /opt/devkitpro
    - echo "export DEVKITPRO=/opt/devkitpro" >> ~/.bashrc
    - echo "export DEVKITARM=/opt/devkitpro/devkitARM" >> ~/.bashrc
    - echo "export PATH=$PATH:/opt/devkitpro/devkitARM/bin" >> ~/.bashrc
    - source ~/.bashrc

script:
    - cd P-Emerald_2
    - make

notifications:
      email: false
