sudo: required
dist: trusty
language: cpp
addons:
    apt:
        sources: [ 'ubuntu-toolchain-r-test']
        packages: ['libstdc++6']
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-4.9 git curl
    - curl -L https://gist.githubusercontent.com/PH111P/959e8ac3aceea74dc2f9f3e2ad3657ab/raw/f9d2ef149cd956c57a0c31f0fcfe4bfd98f9ee3e/devkitARMupdate.pl -o devkitARMupdate.pl
    - chmod +x ./devkitARMupdate.pl
    - sudo ./devkitARMupdate.pl /opt/devkitpro
    - echo "export DEVKITPRO=/opt/devkitpro" >> ~/.bashrc
    - echo "export DEVKITARM=/opt/devkitpro/devkitARM" >> ~/.bashrc
    - echo "export PATH=$PATH:/opt/devkitpro/devkitARM/bin" >> ~/.bashrc
    - source ~/.bashrc

script:
    - cd P-Emerald_2
    - make

notifications:
      email: false
