os: linux
dist: focal
language: cpp

services:
  - docker

install:
  - docker pull devkitpro/devkitarm

script:
  - docker run -e ENABLE_COMPATIBILITY_REPORTING -v $TRAVIS_BUILD_DIR:/perm2 devkitpro/devkitarm /bin/bash -ex /perm2/.travis/docker.sh

notifications:
  email: false

deploy:
  provider: releases
  edge: true
  file:
    - "P-Emerald_2_NOSOUND.nds"
    - "P-Emerald_2_NOSOUND_DESQUID.nds"
    - "P-Emerald_2.nds"
    - "P-Emerald_2_DESQUID.nds"
  draft: true
  on:
    tags: true
