os: linux
dist: focal
language: cpp

services:
  - docker

install:
  - docker pull devkitpro/devkitarm
  - mkdir -p /opt/devkitpro
  - docker cp devkitarm:/opt/devkitpro /opt/devkitpro

script:
  - cd perm2/P-Emerald_2
  - make NOSOUND=1
  - mv P-Emerald_2.nds P-Emerald_2_NOSOUND.nds
  - make DESQUID=1 NOSOUND=1 rebuild
  - mv P-Emerald_2.nds P-Emerald_2_NOSOUND_DESQUID.nds
  - make DESQUID=1 rebuild
  - mv P-Emerald_2.nds P-Emerald_2_DESQUID.nds
  - make rebuild

notifications:
  email: false

deploy:
  provider: releases
  edge: true
  file:
    - "P-Emerald_2_NOSOUND.nds"
    - "P-Emerald_2_NOSOUND_DESQUID.nds"
    - "P-Emerald_2.nds"
    - "P-Emerald_2_DESQUID.nds"
  draft: true
  on:
    tags: true
