os: linux
dist: focal
language: cpp

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-10

script:
  - docker pull devkitpro/devkitarm
  - docker run -p 4000:80 --name devkitarm devkitpro/devkitarm
  - mkdir -p /opt/devkitpro
  - docker cp devkitarm:/opt/devkitpro /opt || true
  - PATH=/opt/devkitpro/tools/bin:$PATH
  - ls /opt/devkitpro/tools/bin
  - ls /opt/devkitpro/tools/
  - ls /opt/devkitpro/
  - ls /opt/
  - cd P-Emerald_2
  - make NOSOUND=1
  - mv P-Emerald_2.nds P-Emerald_2_NOSOUND.nds
  - make DESQUID=1 NOSOUND=1 rebuild
  - mv P-Emerald_2.nds P-Emerald_2_NOSOUND_DESQUID.nds
  - make DESQUID=1 rebuild
  - mv P-Emerald_2.nds P-Emerald_2_DESQUID.nds
  - make rebuild
  - docker container stop devkitarm
  - docker rm -f devkitarm

notifications:
  email: false

deploy:
  provider: releases
  edge: true
  file:
    - "P-Emerald_2_NOSOUND.nds"
    - "P-Emerald_2_NOSOUND_DESQUID.nds"
    - "P-Emerald_2.nds"
    - "P-Emerald_2_DESQUID.nds"
  draft: true
  on:
    tags: true
